# Generated by Django 3.2.25 on 2025-01-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='NewsletterSubscription',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='No Subject', max_length=100),
        ),
    ]
