# Generated by Django 3.2.25 on 2025-01-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20250125_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='submitted_at',
            field=models.DateTimeField(),
        ),
    ]
