# Generated by Django 3.2.25 on 2025-01-25 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20250125_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='temp_field',
        ),
    ]
